/*
 * This file was generated by the Gradle 'init' task.
 */


dependencies {
    api(project(":commandapi-core"))
    api(libs.dev.jorel.commandapi.bukkit.core)
    api(libs.dev.jorel.commandapi.bukkit.nms.common)
    api(libs.dev.jorel.commandapi.bukkit.v1.v19.common)
    api(libs.dev.jorel.commandapi.bukkit.v1.v17.common)
    api(libs.dev.jorel.commandapi.bukkit.v1.v20)
    api(libs.dev.jorel.commandapi.bukkit.v1.v19.v4)
    api(libs.dev.jorel.commandapi.bukkit.v1.v19.v3)
    api(libs.dev.jorel.commandapi.bukkit.v1.v19.v1)
    api(libs.dev.jorel.commandapi.bukkit.v1.v19)
    api(libs.dev.jorel.commandapi.bukkit.v1.v18.v2)
    api(libs.dev.jorel.commandapi.bukkit.v1.v18)
    api(libs.dev.jorel.commandapi.bukkit.v1.v17)
    api(libs.dev.jorel.commandapi.bukkit.v1.v17.v1)
    api(libs.dev.jorel.commandapi.bukkit.v1.v16.v5)
    testImplementation(libs.dev.jorel.commandapi.bukkit.test.tests)
}

description = "commandapi-codecov"

java {
    withJavadocJar()
}
