/*
 * This file was generated by the Gradle 'init' task.
 */

dependencies {
    api(libs.dev.jorel.commandapi.bukkit.core)
    compileOnly(libs.com.google.auto.service.auto.service)
    compileOnly(libs.org.spigotmc.spigot.api)
}

description = "commandapi-annotations"

java {
    withJavadocJar()
}
